from . import res_bank
from . import payment_type_catalog
from . import partner_bank_type_catalog
from . import multipayment_advance_it
from . import res_partner_bank
from . import bank_parameter_it
from . import res_partner
from . import account_journal
from . import format_bank_it