from . import hr_type_document
from . import hr_situation
from . import hr_worker_type
from . import hr_suspension_type
from . import hr_social_insurance
from . import hr_contributions
from . import hr_membership
from . import hr_analytic_distribution
from . import hr_main_parameter
from . import hr_reasons_leave
from . import account_fiscal_year
from . import hr_period